package Controllers.FrontEnd;

import Controllers.Backend.AccountType;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

/**
 * Handles events on the login page.
 */
public class LoginHandler implements Initializable {

    @FXML
    TextField LoginUsername;

    @FXML
    PasswordField LoginPassword;

    @FXML
    Label LoginErrorText;

    /**
     * Handles login button press
     * @param HandleLoginPress event generated by Login Press button
     * @throws IOException handles error in file entry/output
     */
    public void HandleLoginPress (ActionEvent HandleLoginPress) throws IOException {

        try {
            LoginController loginController = new LoginController();
            loginController.AttemptLogin(LoginUsername.getText(), LoginPassword.getText());

            Parent loginView;

            if (LoginController.GetUser().GetAccountType() == AccountType.SystemAdmin) {
                loginView = FXMLLoader.load(getClass().getResource("/Views/Admin/AdminScreen.fxml"));
            } else if (LoginController.GetUser().GetAccountType() == AccountType.User ||
                    LoginController.GetUser().GetAccountType() == AccountType.UnitLeader) {
                loginView = FXMLLoader.load(getClass().getResource("/Views/User/UserScreen.fxml"));
            } else {
                throw new LoginException("Unexpected Error");
            }


            Scene loginViewScene = new Scene(loginView);

            Stage window = (Stage)((Node)HandleLoginPress.getSource()).getScene().getWindow();

            window.setScene(loginViewScene);
            window.show();
        } catch(LoginException e) {
            LoginErrorText.setText(e.getMessage());
        } catch (Exception e) {
            LoginErrorText.setText(e.getMessage());
        }

    }

    /**
     * Handles reset password events
     * @param TriggerResetPassword events generated by Reset Password press button
     * @throws IOException handles error in file entry/output
     */
    public void TriggerResetPassword (ActionEvent TriggerResetPassword) throws IOException {

        Parent passwordReseter;
        passwordReseter = FXMLLoader.load(getClass().getResource("/Views/Login/Reset.fxml"));
        Scene passwordReseterScene = new Scene(passwordReseter);

        Stage window = (Stage)((Node)TriggerResetPassword.getSource()).getScene().getWindow();

        window.setScene(passwordReseterScene);
        window.show();

    }



    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {

    }
}

